/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as OngIndexRouteImport } from './routes/ong.index'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer.profile'
import { Route as VolunteerNotificationsRouteImport } from './routes/volunteer.notifications'
import { Route as VolunteerMapRouteImport } from './routes/volunteer.map'
import { Route as OngVolunteersRouteImport } from './routes/ong.volunteers'
import { Route as OngResourcesRouteImport } from './routes/ong.resources'
import { Route as OngProfileRouteImport } from './routes/ong.profile'
import { Route as OngActionsRouteImport } from './routes/ong.actions'
import { Route as OngNetworkIndexRouteImport } from './routes/ong.network.index'
import { Route as VolunteerActionActionIdRouteImport } from './routes/volunteer.action.$actionId'
import { Route as OngNetworkConnectionIdRouteImport } from './routes/ong.network.$connectionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OngIndexRoute = OngIndexRouteImport.update({
  id: '/ong/',
  path: '/ong/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/volunteer/profile',
  path: '/volunteer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerNotificationsRoute = VolunteerNotificationsRouteImport.update({
  id: '/volunteer/notifications',
  path: '/volunteer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerMapRoute = VolunteerMapRouteImport.update({
  id: '/volunteer/map',
  path: '/volunteer/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OngVolunteersRoute = OngVolunteersRouteImport.update({
  id: '/ong/volunteers',
  path: '/ong/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const OngResourcesRoute = OngResourcesRouteImport.update({
  id: '/ong/resources',
  path: '/ong/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OngProfileRoute = OngProfileRouteImport.update({
  id: '/ong/profile',
  path: '/ong/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OngActionsRoute = OngActionsRouteImport.update({
  id: '/ong/actions',
  path: '/ong/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const OngNetworkIndexRoute = OngNetworkIndexRouteImport.update({
  id: '/ong/network/',
  path: '/ong/network/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerActionActionIdRoute = VolunteerActionActionIdRouteImport.update({
  id: '/volunteer/action/$actionId',
  path: '/volunteer/action/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OngNetworkConnectionIdRoute = OngNetworkConnectionIdRouteImport.update({
  id: '/ong/network/$connectionId',
  path: '/ong/network/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ong/actions': typeof OngActionsRoute
  '/ong/profile': typeof OngProfileRoute
  '/ong/resources': typeof OngResourcesRoute
  '/ong/volunteers': typeof OngVolunteersRoute
  '/volunteer/map': typeof VolunteerMapRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ong/': typeof OngIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/ong/network/$connectionId': typeof OngNetworkConnectionIdRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
  '/ong/network/': typeof OngNetworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ong/actions': typeof OngActionsRoute
  '/ong/profile': typeof OngProfileRoute
  '/ong/resources': typeof OngResourcesRoute
  '/ong/volunteers': typeof OngVolunteersRoute
  '/volunteer/map': typeof VolunteerMapRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ong': typeof OngIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/ong/network/$connectionId': typeof OngNetworkConnectionIdRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
  '/ong/network': typeof OngNetworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/ong/actions': typeof OngActionsRoute
  '/ong/profile': typeof OngProfileRoute
  '/ong/resources': typeof OngResourcesRoute
  '/ong/volunteers': typeof OngVolunteersRoute
  '/volunteer/map': typeof VolunteerMapRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ong/': typeof OngIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/ong/network/$connectionId': typeof OngNetworkConnectionIdRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
  '/ong/network/': typeof OngNetworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ong/actions'
    | '/ong/profile'
    | '/ong/resources'
    | '/ong/volunteers'
    | '/volunteer/map'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/ong/'
    | '/volunteer/'
    | '/ong/network/$connectionId'
    | '/volunteer/action/$actionId'
    | '/ong/network/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ong/actions'
    | '/ong/profile'
    | '/ong/resources'
    | '/ong/volunteers'
    | '/volunteer/map'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/ong'
    | '/volunteer'
    | '/ong/network/$connectionId'
    | '/volunteer/action/$actionId'
    | '/ong/network'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/ong/actions'
    | '/ong/profile'
    | '/ong/resources'
    | '/ong/volunteers'
    | '/volunteer/map'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/ong/'
    | '/volunteer/'
    | '/ong/network/$connectionId'
    | '/volunteer/action/$actionId'
    | '/ong/network/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  OngActionsRoute: typeof OngActionsRoute
  OngProfileRoute: typeof OngProfileRoute
  OngResourcesRoute: typeof OngResourcesRoute
  OngVolunteersRoute: typeof OngVolunteersRoute
  VolunteerMapRoute: typeof VolunteerMapRoute
  VolunteerNotificationsRoute: typeof VolunteerNotificationsRoute
  VolunteerProfileRoute: typeof VolunteerProfileRoute
  OngIndexRoute: typeof OngIndexRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  OngNetworkConnectionIdRoute: typeof OngNetworkConnectionIdRoute
  VolunteerActionActionIdRoute: typeof VolunteerActionActionIdRoute
  OngNetworkIndexRoute: typeof OngNetworkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/': {
      id: '/ong/'
      path: '/ong'
      fullPath: '/ong/'
      preLoaderRoute: typeof OngIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/volunteer/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/notifications': {
      id: '/volunteer/notifications'
      path: '/volunteer/notifications'
      fullPath: '/volunteer/notifications'
      preLoaderRoute: typeof VolunteerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/map': {
      id: '/volunteer/map'
      path: '/volunteer/map'
      fullPath: '/volunteer/map'
      preLoaderRoute: typeof VolunteerMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/volunteers': {
      id: '/ong/volunteers'
      path: '/ong/volunteers'
      fullPath: '/ong/volunteers'
      preLoaderRoute: typeof OngVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/resources': {
      id: '/ong/resources'
      path: '/ong/resources'
      fullPath: '/ong/resources'
      preLoaderRoute: typeof OngResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/profile': {
      id: '/ong/profile'
      path: '/ong/profile'
      fullPath: '/ong/profile'
      preLoaderRoute: typeof OngProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/actions': {
      id: '/ong/actions'
      path: '/ong/actions'
      fullPath: '/ong/actions'
      preLoaderRoute: typeof OngActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/network/': {
      id: '/ong/network/'
      path: '/ong/network'
      fullPath: '/ong/network/'
      preLoaderRoute: typeof OngNetworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/action/$actionId': {
      id: '/volunteer/action/$actionId'
      path: '/volunteer/action/$actionId'
      fullPath: '/volunteer/action/$actionId'
      preLoaderRoute: typeof VolunteerActionActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong/network/$connectionId': {
      id: '/ong/network/$connectionId'
      path: '/ong/network/$connectionId'
      fullPath: '/ong/network/$connectionId'
      preLoaderRoute: typeof OngNetworkConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  OngActionsRoute: OngActionsRoute,
  OngProfileRoute: OngProfileRoute,
  OngResourcesRoute: OngResourcesRoute,
  OngVolunteersRoute: OngVolunteersRoute,
  VolunteerMapRoute: VolunteerMapRoute,
  VolunteerNotificationsRoute: VolunteerNotificationsRoute,
  VolunteerProfileRoute: VolunteerProfileRoute,
  OngIndexRoute: OngIndexRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  OngNetworkConnectionIdRoute: OngNetworkConnectionIdRoute,
  VolunteerActionActionIdRoute: VolunteerActionActionIdRoute,
  OngNetworkIndexRoute: OngNetworkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
