/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as VolunteerActionActionIdRouteImport } from './routes/volunteer.action.$actionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerActionActionIdRoute = VolunteerActionActionIdRouteImport.update({
  id: '/volunteer/action/$actionId',
  path: '/volunteer/action/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onboarding' | '/volunteer/' | '/volunteer/action/$actionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onboarding' | '/volunteer' | '/volunteer/action/$actionId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/volunteer/'
    | '/volunteer/action/$actionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  VolunteerActionActionIdRoute: typeof VolunteerActionActionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/action/$actionId': {
      id: '/volunteer/action/$actionId'
      path: '/volunteer/action/$actionId'
      fullPath: '/volunteer/action/$actionId'
      preLoaderRoute: typeof VolunteerActionActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  VolunteerActionActionIdRoute: VolunteerActionActionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
