/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as OngNeedIndexRouteImport } from './routes/ong-need.index'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer.profile'
import { Route as VolunteerNotificationsRouteImport } from './routes/volunteer.notifications'
import { Route as VolunteerMapRouteImport } from './routes/volunteer.map'
import { Route as VolunteerActionActionIdRouteImport } from './routes/volunteer.action.$actionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/volunteer/',
  path: '/volunteer/',
  getParentRoute: () => rootRouteImport,
} as any)
const OngNeedIndexRoute = OngNeedIndexRouteImport.update({
  id: '/ong-need/',
  path: '/ong-need/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/volunteer/profile',
  path: '/volunteer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerNotificationsRoute = VolunteerNotificationsRouteImport.update({
  id: '/volunteer/notifications',
  path: '/volunteer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerMapRoute = VolunteerMapRouteImport.update({
  id: '/volunteer/map',
  path: '/volunteer/map',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerActionActionIdRoute = VolunteerActionActionIdRouteImport.update({
  id: '/volunteer/action/$actionId',
  path: '/volunteer/action/$actionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/volunteer/map': typeof VolunteerMapRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ong-need/': typeof OngNeedIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/volunteer/map': typeof VolunteerMapRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ong-need': typeof OngNeedIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/volunteer/map': typeof VolunteerMapRoute
  '/volunteer/notifications': typeof VolunteerNotificationsRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ong-need/': typeof OngNeedIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/volunteer/action/$actionId': typeof VolunteerActionActionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/volunteer/map'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/ong-need/'
    | '/volunteer/'
    | '/volunteer/action/$actionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/volunteer/map'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/ong-need'
    | '/volunteer'
    | '/volunteer/action/$actionId'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/volunteer/map'
    | '/volunteer/notifications'
    | '/volunteer/profile'
    | '/ong-need/'
    | '/volunteer/'
    | '/volunteer/action/$actionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  VolunteerMapRoute: typeof VolunteerMapRoute
  VolunteerNotificationsRoute: typeof VolunteerNotificationsRoute
  VolunteerProfileRoute: typeof VolunteerProfileRoute
  OngNeedIndexRoute: typeof OngNeedIndexRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
  VolunteerActionActionIdRoute: typeof VolunteerActionActionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/volunteer'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ong-need/': {
      id: '/ong-need/'
      path: '/ong-need'
      fullPath: '/ong-need/'
      preLoaderRoute: typeof OngNeedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/volunteer/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/notifications': {
      id: '/volunteer/notifications'
      path: '/volunteer/notifications'
      fullPath: '/volunteer/notifications'
      preLoaderRoute: typeof VolunteerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/map': {
      id: '/volunteer/map'
      path: '/volunteer/map'
      fullPath: '/volunteer/map'
      preLoaderRoute: typeof VolunteerMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/action/$actionId': {
      id: '/volunteer/action/$actionId'
      path: '/volunteer/action/$actionId'
      fullPath: '/volunteer/action/$actionId'
      preLoaderRoute: typeof VolunteerActionActionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  VolunteerMapRoute: VolunteerMapRoute,
  VolunteerNotificationsRoute: VolunteerNotificationsRoute,
  VolunteerProfileRoute: VolunteerProfileRoute,
  OngNeedIndexRoute: OngNeedIndexRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
  VolunteerActionActionIdRoute: VolunteerActionActionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
